### ISSUE TITLE
can't download occurrences file

### ISSUE THREAD

**Issue by anyonggang** [jivelasquezt/WhereNext-Pkg#1]
Error in utils::download.file(url = aurl, destfile = fn, method = "auto", : 无法打开URL'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_COL_0_sp.rds'
 
 An error ocurred downloading country shapefile.
Check your internet connection, search parameters and/or GBIF credentials and try again

**Comment by jivelasquezt** [comment]
This issue is external to wherenext, it has to do with the external servers that the getData function in raster usses to download country shapefiles being down (usually temporarily, for maintenance). A workaround is to provide wherenext with a country or area of interest shapefile instead.
